### PR TITLE
Fix defaults for nested objects in preview

### LINKED ISSUE #84: Defaults not working in the preview for nested elements, when data is undefined
When `data` is undefined, the defaults are correctly initialized in the preview only for top level schema elements. 

To reproduce: add a control for `personalData/drivingSkill` and open preview. The default value of `7` is not set.

### PR DESCRIPTION
**Pull request by AlexandraBuzila**
Data for nested objects needs to be initialized for AJV to validate and set defaults

Fixes #84

### CODE REVIEW

File: src/editor/components/preview/ReactMaterialPreview.tsx [hunk 1]
```diff
@@ -11,20 +11,21 @@ import {
...
 export const ReactMaterialPreview: React.FC = () => {
   const schema = useExportSchema();
   const uischema = useExportUiSchema();
-
+  const previewData = useMemo(() => generateDataForPreview(schema), [schema]);
   const ajv = createAjv(previewOptions);
   return (
     <JsonForms
       ajv={ajv}
-      data={{}}
```
Comment (eneufeld) [inline src/editor/components/preview/ReactMaterialPreview.tsx:27]: the old code for data is enough

Comment (AlexandraBuzila) [reply src/editor/components/preview/ReactMaterialPreview.tsx:27]: Validation/defaults don't work in react either without the initialized object.

File: src/editor/components/preview/data.ts [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+): object => {
+  if (schema && schema.type === 'object' && schema.properties) {
+    Object.entries(schema.properties).forEach(([key, value]) => {
+      if (value?.type === 'object') {
+        data[key] = generateDataForPreview(value, {});
+      }
+    });
+  }
+  return data;
+};
```
Comment (sdirix) [inline src/editor/components/preview/data.ts:22]: I would place the code in `schema.ts` and let it work on our intermediate format, not the "real/export" format.

- All schema related logic is then in the same place
- All edge cases are then implicitly handled, as for example an object doesn't need to have `type: 'object'`, it could also only have `properties` which automatically makes it to an object.

Comment (AlexandraBuzila) [reply src/editor/components/preview/data.ts]: Moved the method to `schema.ts`

File: jsonforms-editor/src/editor/components/preview/ReactMaterialPreview.tsx [hunk 3]
```diff
@@ -11,20 +11,21 @@ import {
...
 
+import { generateEmptyData } from '../../../core/model';
 import { useExportSchema, useExportUiSchema } from '../../../core/util/hooks';
 import { previewOptions } from './options';
 
 export const ReactMaterialPreview: React.FC = () => {
   const schema = useExportSchema();
   const uischema = useExportUiSchema();
-
+  const previewData = useMemo(() => generateEmptyData(schema), [schema]);
```
Comment (sdirix) [inline jsonforms-editor/src/editor/components/preview/ReactMaterialPreview.tsx:23]: `generateEmptyData` expects our custom `SchemaElement` type but it gets the exported JSON Schema. This works by chance because our custom `SchemaElement` also has a `type` which will be set to `object` for objects ;)

This is easily overlooked as the `schema` type is `any` here. We should `buildJsonSchema` in `schema.ts` to return ` JsonSchema`, then Typescript would complain about the mismatched types here.

I would like to suggest the following:
1. Adapt the type of `buildJsonSchema` and other methods in `schema.ts` which are not correctly typed.
2. Adapt the `useExportSchema` custom hook to take an optional boolean parameter. If it's set to true it should also return the original schema, e.g. `{schema, exportSchema}`, otherwise it should just return the exportSchema
3. Do the same for `useExportUiSchema` for consistency.
4. Use the new hook variants in the previews to calculate the previewData and to set the correct `schema`.
5. (Optional but recommended) remove the `useTransform` and `useEffectAfterInit` custom hooks and just replace it with `useMemo`. They are no longer needed.

Comment (AlexandraBuzila) [reply jsonforms-editor/src/editor/components/preview/ReactMaterialPreview.tsx]: Ah, I missed that detail. I fixed it now and added types to the methods from `schems.ts`. However, I kept the `useExportSchema` hook as it is: in all other cases where the export schema was needed, the original one was not. And in case the original schema is needed, it's readily available via the `useSchema` hook. Modifying the `useExportSchema` and `useExportUiSchema` hooks to return the original schema on request only leads to type checking of the result everywhere the hooks are used. 
But if you feel strongly about it, I can change it.

File: jsonforms-editor/src/core/model/schema.ts [hunk 4]
```diff
@@ -346,9 +354,12 @@ export const cleanLinkedElements = (schema: SchemaElement | undefined): any => {
       break;
     case ARRAY:
       if (Array.isArray(schema.items)) {
-        schema.items = schema.items.map(cleanLinkedElements);
+        schema.items =
+          (schema.items
+            .map(cleanLinkedElements)
+            .filter((item) => item !== undefined) as SchemaElement[]) ?? [];
```
Comment (sdirix) [inline jsonforms-editor/src/core/model/schema.ts:360]: I think this `??` will never return the right side and can be removed.
